### ISSUE TITLE
Breakpoints not generated with BUILDSNA V2

### ISSUE THREAD

**Issue by CurlyPaul** [EdouardBERGE/rasm#17]
I seem to be having trouble using BUILDSNA V2 and breakpoints at the same time. 

In my entry file I've got:

    BUILDSNA V2
    BANKSET 0
    ORG #4000 
    RUN #4000

and the the CLI

    -sw -sl -sq -sb

SNA file is generated but no breakpoints are present in WinApe

If I remove V2 the breakpoints load, but I'd like the firmware present for this particular thing. Not a huge problem, just reporting

**Comment by EdouardBERGE** [comment]
there is no chunk in V2 format, as snapshot is specified!
https://www.cpcwiki.eu/index.php/Format:SNA_snapshot_file_format

but as it's not obvious, i may add a warning at output

**Comment by CurlyPaul** [comment]
Ah yes I see, I can't do this. OK, thank you very much for the fast reply
