### ISSUE TITLE
Building AT2 player broken in recent builds

### ISSUE THREAD

**Issue by pelrun** [EdouardBERGE/rasm#20]
Commit 496467d6589fcc87a82181d249c4d9a818de7482 caused significant changes in the output binary when building PlayerAkmTester_CPC.asm, and the new binary doesn't work.

MD5sums for before and after the commit are below; it's a stepwise change and no other commits since v1.3 produce any differences in the output.

07da2b69ce681b5913c19141877f389c  good.bin
7183ba06e706148513e890e492722ce6  bad.bin

**Comment by EdouardBERGE** [comment]
the problem was with EQU value used before declaration of the EQU
almost undefined behaviour (most of the time, truncating the expression after the EQU value and leaving evaluation without error)
