### ISSUE TITLE
opcodes_first_bytes.asm has duplicated labels

### ISSUE THREAD

**Issue by rgiot** [EdouardBERGE/rasm#23]
```
opcode_dec_hl             EQU  0x2b
opcode_dec_hl             EQU  0x35
```

**Comment by EdouardBERGE** [comment]
yeah, who give me this? ^_^
will convert HL to MHL (memory HL) where it's supposed to be

**Comment by EdouardBERGE** [comment]
i guess the whole file must be rewrite with a proper naming convention

**Comment by rgiot** [comment]
There are yet at least these additional ones ;)
 
opcode_ld_hl_nnnn         EQU  0x21
opcode_ld_hl_nnnn         EQU  0x2a

**Comment by EdouardBERGE** [comment]
https://github.com/EdouardBERGE/rasm/commit/18f57a19d5889e9e4db192369693e3823cba676c
