### ISSUE TITLE
Align odd

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#25]
Hi,

Is there a way to align code on an odd address?
AFIK, there is no "Align odd".

I would need it for a self modifying code, e.g.:
`my_smc: ld de,0x10F0 ; 11 F0 10`

If this line was odd aligned, F0 10 would be even aligned,
and I could navigate between the 2 addresses with INC L/DEC L instead of INC HL/DEC HL.
```
ld hl,my_smc+1
ld a,(hl)
;;
;; Do sth.
;;
inc l
ld a,(hl)
;;
;; Do sth.
;;
dec l
;;
;; Do sth.
;;
inc l
;;
;; Etc.
```

Do you know a way to achieve that?

**Comment by EdouardBERGE** [comment]
You may align on even address then use +1 to be odd

ALIGN 2 : NOP ; same as 'align odd'

Or you can use dedicated instruction for array inc/dec optimisation => CONFINE

You need to "run" in a 5 bytes array? => CONFINE 5

Then Rasm will garantee you that the array will not cross over MSB change

**Comment by anrikun** [comment]
Thank you Edouard.
CONFINE looks really useful but I can't see it in the documentation.
Isn't it missing?

**Comment by anrikun** [comment]
Nice!
Merci beaucoup Edouard!
