### ISSUE TITLE
Any new release soon?

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#29]
Hello Edouard,
Are you planning on making a new release soon?
I can't get the files necessary to compile RASM without installing Visual Studio entirely and I'm low on disk space.

**Comment by EdouardBERGE** [comment]
i publish a windows release with latest sources
https://github.com/EdouardBERGE/rasm/releases/tag/build25092022

**Comment by anrikun** [comment]
:clap:

**Comment by anrikun** [comment]
Windows Defender (Win7) detects this trojan when I download the new RASM.exe:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505&enterprise=0

**Comment by anrikun** [comment]
What's even strange is that it triggers this false positive only on 1 of my two computers, both (old) Win7s. Too bad the computer that wipes out RASM.exe is precisely the one I use to write and compile my code! :laughing:

**Comment by EdouardBERGE** [comment]
Not only false positive but same executable changing from version to another will trigger Defender alert, you need to configure a directory exception to keep quiet Defender.
"New" policy is so strict that a few years ago Defender was deleting downloaded App from Microsoft store ^_^
