### ISSUE TITLE
Variable clash when including Arkos Tracker 2's PlayerAKM.asm

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#31]
Hi,
I've tried to include Arkos Tracker 2's PlayerAKM.asm into my project.
When compiling, I get error : `cannot create variable [COUNTER] as there is already a label with the same name`
My project has indeed a `counter `label and Arkos declares a `counter `variable.
Obviously if I rename my label, the problem is solved.
But I was wondering if there was a way to "encapsulate" the included file so that this kind of clash could be avoided.
Or to automatically add a suffix to a variable name when a label with the same name already exists. 
I've searched through the documentation without success.
Thank you in advance for your help.

**Comment by EdouardBERGE** [comment]
you can use MODULE directive to open a module (do not forgot to close it) and encapsulate the player
you will have to change your CALLS to the player
http://rasm.wikidot.com/syntaxe:labels
