### ISSUE TITLE
Add pow(x,y) function 

### ISSUE THREAD

**Issue by BetaSoftCologne** [EdouardBERGE/rasm#34]
I would like to be able to evaluate expressions like x^y (x raised to the power of y) or pow(x,y) in my source.

**Comment by Reymon-Real** [comment]
I understood that you wanted to parse expressions. For that you have to implement a lexical analyser.

**Comment by EdouardBERGE** [comment]
pow(x,y) = exp(y*log(x))

so...

:)

**Comment by EdouardBERGE** [comment]
functions with more than one parameter will happen :)

fmod, atan2, hypot, ldexp, fdim, step, fmax, fmin, clamp, lerp, isgreater, isless, remainder

nothing else?
