### ISSUE TITLE
How do I compile a program written in ASM for the Amstrad CPC and run it on retro virtual machine? 

### ISSUE THREAD

**Issue by Reymon-Real** [EdouardBERGE/rasm#38]
Although I see the documentation, I do not understand how to do it. On the one hand it compiles the program and I see the binary, but on the other hand it gives me a “.bin” file and I want a sna or dsk file. I saw the SAVE part but it always tells me that it does not find the file.

**Comment by EdouardBERGE** [comment]
There is some examples in the documentation to create snapshots

http://rasm.wikidot.com/dev:supersnap
http://rasm.wikidot.com/keywords:memory

I'm not the author of RVM so i cannot help you with this emulator. Use ACE-DL :p
http://www.roudoudou.com/ACE-DL/
It will benefit extra informations of the snapshot

**Comment by Reymon-Real** [comment]
Thanks, I just don't understand the documentation.

**Comment by Reymon-Real** [comment]
@EdouardBERGE 
Thanks, I don't understand the documentation on the sna and dsk part.
Here is what I have in my Makefile to see what my error is.

src := src
bin := bin
rasm := rasm_win64

all:
	@$(rasm) -I $(src) -utf8 -sw -o $(bin)/main main.asm
	@$(rasm) -I $(bin) -utf8 -eo main.bin
	@RetroVirtualMachine

**Comment by EdouardBERGE** [comment]
once rasm has compiled your main.asm, there is nothing to do with the binary main.bin (except putting it in an emulator)
you must add in your main.asm some lines (to output a file, a snapshot or a DSK, don't know what you want)

**Comment by EdouardBERGE** [comment]
```
buildsna
bankset 0
org #100
run #100
; your code here

```
this will generate a snapshot 
see the links i sent you for explanations of each directives

**Comment by Reymon-Real** [comment]
@EdouardBERGE 
Thank you very much
