### ISSUE TITLE
Is there any way to disable read and leave the rest of the forms to include files?

### ISSUE THREAD

**Issue by Reymon-Real** [EdouardBERGE/rasm#40]
I am making an OS following the POSIX 1990 standard. This is a university project I am in, but I have encountered the problem that a POSIX 1990 function is called read and the Assembler interprets it as if it were read to include files.

I wanted to know if there is a way to disable the read and only leave the other ways to include files.

**Comment by EdouardBERGE** [comment]
i'm afraid you will have to replace occurences of 'read' in your source code

**Comment by Reymon-Real** [comment]
@EdouardBERGE
Ok, thanks for the clarification. I really liked RASM, although I can not put read as a tag, I will continue to use it because it is very simple for its ease of use unlike others like Z88k (it cost me a lot to make it work to compile the code) and also RASM is very complete unlike cpctelera that lacks to implement mnemonics that RASM does have (it is not exactly like RASM, but it can compile to the Z80).

I say this to let you know that at least for my part I love RASM.
