### ISSUE TITLE
Cannot export .tap file

### ISSUE THREAD

**Issue by BogdanTheGeek** [EdouardBERGE/rasm#41]
I cannot find a way to export .tap files
Reading the source code, i don't see where `ae->forcetape` even is set...
```
rasm X.z80 -ot X.tap
```

**Comment by EdouardBERGE** [comment]
http://rasm.wikidot.com/keywords:memory

you need to start your source with BUILDTAPE directive

that will export a .CDT file (which is supposed to be the same thing as TAP file)

**Comment by BogdanTheGeek** [comment]
Thank for the response, I think we are using different terminologies. I tried building it with the BUILDTAPE directive, but I cannot load the .tap into my spectrum emulator.
Also, Is there no way to produce a .bin and a .tap without modifying the source?

**Comment by EdouardBERGE** [comment]
you can force binary output using SAVE directive

you will get a CDT (tap) and a binary :)
