### ISSUE TITLE
Is it possible to generate binary with rasm as if it were a form similar to object files?

### ISSUE THREAD

**Issue by Reymon-Real** [EdouardBERGE/rasm#42]
It is very tedious to have to recompile every single file all the time (even with a Makefile it is tedious) and I wanted to know if there is a way to generate binary files which can then be assembled into a sna or similar.

**Comment by EdouardBERGE** [comment]
you can include all your files in a single one and assemble everything with one command, you can save any number of binaries in a single row and it will be done quickly. Forget makefile, it's slow

**Comment by Reymon-Real** [comment]
@EdouardBERGE 
OK, thanks for the suggestion! Could you still consider adding a feature for generating binary files similar to object files? This would be really helpful for people like me who prefer working with multiple files and using Makefile. I understand it takes work and time, but it would be greatly appreciated. I really consider RASM to be the best assembler for the Z80, and with a few more features, it could be even more comfortable for different programmers.

**Comment by Reymon-Real** [comment]
@EdouardBERGE An apology for replying 2 days later, I was busy.

**Comment by Reymon-Real** [comment]
@EdouardBERGE I just want to clarify that what I am asking for is a suggestion and that I will continue to use RASM regardless of whether the feature is added or not.

**Comment by EdouardBERGE** [comment]
I added years ago something similar to SDCC object files but there is no documentation on objects, so i never finished.

If you want to assemble many files separately for fun, you can already export/import symbol to keep symbols values when assembling other files

**Comment by Reymon-Real** [comment]
@EdouardBERGE 
Well, that solves my doubt.
Thank you for your time and attention.
