### ISSUE TITLE
Help with saving my loader as .CDT

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#43]
Hi Edouard,

I'm a bit confused about how to save my loader as a .CDT file. I've added the following lines, as per the documentation:
```
buildtape
save 'loader.bin',init,end-init,TAPE
```
However, I’m getting the error: "Cannot autoselect TAPE, please specify a filename after TAPE arg."

I then tried this:
`save 'loader.bin',init,end-init,TAPE,'what_is_this'`

This results in two files:
-     rasmoutput.cdt
-     what_is_this

I was expecting to get a single .CDT file, but obviously, I’m doing something wrong.

Can you help me figure this out?

Thanks,
Henri

**Comment by EdouardBERGE** [comment]
you are right and the doc is wrong, i will fix the doc, thanks
simply add .cdt after what_is_this (or tzx for spectrum)

**Comment by anrikun** [comment]
Thank you Edouard.
And removing `buildtape` solved the issue of the extra `rasmoutput.cdt`.
I realized that `buildtape` serves a different purpose.

**Comment by EdouardBERGE** [comment]
buildtape can output a single CDT automatically when you do not want to use SAVE

happy for you :)
