### ISSUE TITLE
Petits soucis dans la documentation

### ISSUE THREAD

**Issue by anrikun** [EdouardBERGE/rasm#44]
Salut Edouard,

Juste 2 petits soucis remarqués dans la doc :

Il est écrit : 

> SETSNA registre, valeur ; usage à 2 paramètres
> SETSNA CRTC_REG, index, valeur ; usage à 3 paramètres

au lieu de `SNASET`.

Par ailleurs, l'option super utile de la ligne de commande `-Dvariable=value` n'est pas mentionnée.

**Comment by EdouardBERGE** [comment]
Merci, c'est corrigé!
Et bien vu ;)

**Comment by anrikun** [comment]
Quelle rapidité 😁

**Comment by LTFMIKE** [comment]
Rapide comme l’éclair Roud 👍💪Le 25 oct. 2024 à 19:21, Henri MEDOT ***@***.***> a écrit :﻿
Quelle rapidité 😁

**Comment by anrikun** [comment]
En fait, je viens de remarquer qu'il faut absolument que la variable de `-Dvariable=value` soit en **majuscules** sinon elle est ignorée.
Donc il faudrait peut-être le mentionner.
`-DVARIABLE=value`

**Comment by EdouardBERGE** [comment]
Hmmm nan c'est ma faute, il faudrait la passer en majuscule automatiquement
J'ai trop l'habitude de toujours les définir en majuscules...
Merci!

**Comment by EdouardBERGE** [comment]
hop :)
https://github.com/EdouardBERGE/rasm/commit/b4fc0fc31fdf8f80d1a310f865619d23815b3d54
