### ISSUE TITLE
Could standard libraries be added to rasm?

### ISSUE THREAD

**Issue by Reymon-Real** [EdouardBERGE/rasm#47]
Nothing complex or otherworldly, just simple things like macros.

For example:

```
CRTC_CONFIG CRTC_REG_Z, CRTC_REG_Z_STD_VALUE
```
```
Label:
Resp 12 ;; Reserve 12 bytes of stack.
;; Code.
Free_stack 12 ;; Return sp to its original value
ret
```

I mean you have macros like that.

You could also have labels for basic calculations like powers and roots.

They would have to be labels/macros that don't depend on the operating system.

It would mainly be basic mathematical operations and macros that summarize calling conventions.

RASM should be able to search in "standard" directories if used, or in any case, separate files that come by default when installing RASM and maintain independence while the user can choose whether or not to use these files.

**Comment by Reymon-Real** [comment]
I could contribute macros and CRTC configuration tags; and memory cleanup.

**Comment by Reymon-Real** [comment]
I want to make it clear that this is just a suggestion.

This is a bad joke:

User: Proposing the most absurd thing you've never heard before.

Me in my mind when I hear it: Pretend to listen to him and give him a polite excuse to refuse.

**Comment by EdouardBERGE** [comment]
hi
a few years ago, i was wondering if i should add variables (like every system calls as defines)
but that's a different project, people may want particular naming conventions, etc.
you may want to start a coding website or something?
regards

**Comment by Reymon-Real** [comment]
@EdouardBERGE 

I understand. In that case you could create a small separate RASM repository where the "standard" or "official" RASM library could be placed.

It could be mainly maintained by the community so you could concentrate on RASM.

You should only define the nomenclature, conventions and other things to be able to contribute to the project.

This would be my last suggestion until I come up with something crazy :v

Thanks for making RASM so good.

**Comment by Reymon-Real** [comment]
@EdouardBERGE 

I forgot to mention that since it is a separate repository from RASM, people can choose to install it or not.

I only mention this because I'm not comfortable explaining everything even though it is understandable without the explanation.

An apology for the inconvenience.
