### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by Reymon-Real** [EdouardBERGE/rasm#49]
When I make some jumps with the `jp label.type.process` instruction RASM translates it one memory address up or down the jump.

I first made sure it wasn't an emulator issue or a problem in my code.

After verifying that, I manually changed the binary (I use the WinApe emulator) and then re-ran the code from scratch.

My code worked, then to finish checking if it was a bug, I opened the binary with an editor and verified that it had indeed been translated incorrectly.

The bug only occurred with the following way I organized my code.

```
RAM

CALL .manager.crtc
JP kernel.proccess.ram

.manager.crtc
LD A, 0
OUT (#BC), A
LD A, #3F
OUT (#BD), A
RET

```

The bug occurs when I jump to the kernel. When translating, it translates one memory address higher.

This only happens specifically when it is a jump with JP, and the memory address has a structure like the one I showed in the example.

**Comment by EdouardBERGE** [comment]
your programm cannot be assembled so i added kernel.proccess.ram at the end
and the jump is ok so...
give me an example of wrong assembling maybe ;)

**Comment by Reymon-Real** [comment]
@EdouardBERGE That was just one example of how I had my code organised.

I noticed that specifically when there is a large distance between memory addresses, and the code is organised as in the example I gave, the bug I mentioned comes up.

I will make a working example and provide it.

Just give me a moment, you may have already fixed it, because I'm using the penultimate version of RASM and when I wrote the issu I didn't realise there was already a new version.

I will check if the bug still persists in the latest version.

**Comment by Reymon-Real** [comment]
@EdouardBERGE I have tested and it seems that it is no longer in this latest version.

Apologies for the inconvenience.
