### ISSUE TITLE
Default build target fails

### ISSUE THREAD

**Issue by cpcitor** [EdouardBERGE/rasm#6]
## Summary

Building with default procedure `git clone ; make` fails.

## Steps to reproduce

```bash
git clone https://github.com/EdouardBERGE/rasm
cd rasm
# Read ReadMe, see no build instructions
make
```

## Observed result

```gcc
cc rasm.c -lm -lrt -march=native -o rasm.exe -g -pthread -DRDD
rasm.c:84:10: fatal error: ../tools/library.h: Aucun fichier ou dossier de ce type
   84 |  #include"../tools/library.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:10 : debug] Erreur 1
```

## Proper fix

May I suggest to either make "prod" the default target, like this:

```makefile
.PHONY: prod debug clean default

default: prod
```

...or add something in the ReadMe, like "to build, issue `make prod`, as the default target `debug` requires my local tools that are not distributed"?

**Comment by EdouardBERGE** [comment]
thank you, i updated the makefile ;)
